apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-pv
  namespace: airflow
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  storageClassName: standard
  hostPath:
    path: "/Users/patcharanat.pa/td88/free-project-workspace/airflow/dags"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs-pv
  namespace: airflow
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  storageClassName: standard
  hostPath:
    path: "/Users/patcharanat.pa/td88/free-project-workspace/airflow/logs"
